FORMAT: 1A
HOST: http://atomic.logsdon.io

# atomic
API for presenting questionnaire answers

## Resource Collection [/]

A list of available resources.

### List all Resources [GET]
+ Response 200 (application/json)

        [{
            "label": "Resource Collection",
            "url": "http://atomic.logsdon.io/"
        },{
            "label": "Prompts Collection",
            "url": "http://atomic.logsdon.io/prompts"
        },{
            "label": "Retrieve a Prompt",
            "url": "http://atomic.logsdon.io/prompts/{slug}"
        },{
            "label": "Prompt's Responses Collection",
            "url": "http://atomic.logsdon.io/prompts/{slug}/responses"
        }]

## Prompts Collection [/prompts]
A list of all available prompts.

### List all Prompts [GET]
+ Response 200 (application/json)

        [{
            "id": 1,
            "prompt": "Let’s start with the basics",
            "slug": "basics",
            "url": "http://atomic.logsdon.io/prompts/basics",
            "created_at": "2014-03-14 14:13:00"
        },{
            "id": 2,
            "prompt": "Where did you hear about Atomic?",
            "slug": "hear-about-atomic",
            "url": "http://atomic.logsdon.io/prompts/hear-about-atomic",
            "created_at": "2014-03-14 14:13:00"
        },{
            "id": 3,
            "prompt": "Why are you applying to Atomic?",
            "slug": "why-apply",
            "url": "http://atomic.logsdon.io/prompts/why-apply",
            "created_at": "2014-03-14 14:13:00"
        },{
            "id": 4,
            "prompt": "Tell me about the first program you were proud of.",
            "slug": "first-program",
            "url": "http://atomic.logsdon.io/prompts/first-program",
            "created_at": "2014-03-14 14:13:00"
        },{
            "id": 5,
            "prompt": "Do you have any hobby projects?",
            "slug": "hobby-projects",
            "url": "http://atomic.logsdon.io/prompts/hobby-projects",
            "created_at": "2014-03-14 14:13:00"
        },{
            "id": 6,
            "prompt": "What is your favorite programming language? Why? What would you do to improve it?",
            "slug": "favorite-language",
            "url": "http://atomic.logsdon.io/prompts/favorite-language",
            "created_at": "2014-03-14 14:13:00"
        },{
            "id": 7,
            "prompt": "What are you planning on learning next?",
            "slug": "learning-plans",
            "url": "http://atomic.logsdon.io/prompts/learning-plans",
            "created_at": "2014-03-14 14:13:00"
        },{
            "id": 8,
            "prompt": "Tell me about a time when you were assigned a project that relied on technology unfamiliar to you.",
            "slug": "unfamiliar-technology",
            "url": "http://atomic.logsdon.io/prompts/unfamiliar-technology",
            "created_at": "2014-03-14 14:13:00"
        },{
            "id": 9,
            "prompt": "Show me some interesting code you’ve written and walk me through it.",
            "slug": "interesting-code",
            "url": "http://atomic.logsdon.io/prompts/interesting-code",
            "created_at": "2014-03-14 14:13:00"
        },{
            "id": 10,
            "prompt": "Tell me about a time you failed at something. What did you learn from the experience?",
            "slug": "failure",
            "url": "http://atomic.logsdon.io/prompts/failure",
            "created_at": "2014-03-14 14:13:00"
        },{
            "id": 11,
            "prompt": "Conflict is a part of life. Describe a time to me where you were involved in a conflict. How did you resolve it?",
            "slug": "conflict",
            "url": "http://atomic.logsdon.io/prompts/conflict",
            "created_at": "2014-03-14 14:13:00"
        },{
            "id": 12,
            "prompt": "How do you deal with situations where you know you can’t deliver?",
            "slug": "cannot-deliver",
            "url": "http://atomic.logsdon.io/prompts/cannot-deliver",
            "created_at": "2014-03-14 14:13:00"
        },{
            "id": 13,
            "prompt": "Show me how you would improve this autobiography document.",
            "slug": "improve",
            "url": "http://atomic.logsdon.io/prompts/improve",
            "response": { ... },
            "created_at": "2014-03-14 14:13:00"
        }]
        
## Prompt [/prompts/{slug}]
A single Prompt object with all its details

The Prompt resource has the following attributes:

- id
- prompt
- slug
- created_at

+ Parameters
    + slug (required, string, `basics`) ... String `slug` of the Prompt to retrieve.

### Retrieve a Prompt [GET]
+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "prompt": "Let’s start with the basics",
                "slug": "basics",
                "url": "http://atomic.logsdon.io/prompts/basics",
                "created_at": "2014-03-14 14:13:00"
            }

## Prompt's Responses Collection [/prompts/{slug}/responses]
A collection of a single Prompt object's responses.

+ Parameters
    + slug (required, string,  `basics`) ... String `slug` of the Prompt to retrieve Responses.
    
### Retrieve a Prompts Responses [GET]
+ Response 200 (application/json)

    + Body
        
            [{
                "id": 1,
                "response": {
                    "name": "Shane Logsdon",
                    "twitter": "https://twitter.com/shanelogsdon",
                    "linked_in": "http://www.linkedin.com/in/shanelogsdon",
                    "git_hub": "https://github.com/slogsdon",
                    "website_or_blog": "http://shane.logsdon.io",
                    "presentations": null,
                    "publications": null,
                    "applications_in_app_stores": null,
                    "other_links": null,
                    "is_united_states_citizen_or_permanent_resident": true
                },
                "url": "http://atomic.logsdon.io/prompts/basics/responses/1",
                "created_at": "2014-03-15 20:00:00"
            }]